services:
  clipsmart-python:
    container_name: clipsmart-py
    build: 
      context: ./python_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      WEBSHARE_USERNAME: ${WEBSHARE_USERNAME}
      WEBSHARE_PASSWORD: ${WEBSHARE_PASSWORD}
      PORT: ${PORT}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_PORT: ${FLASK_PORT}
      FLASK_HOST: ${FLASK_HOST}
      PROXY_USERNAME: ${PROXY_USERNAME}
      PROXY_PASSWORD: ${PROXY_PASSWORD}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
       
    networks:
      - clipsmartnetwork
      
  clipsmart-frontend:
    container_name: clipsmart-fe
    depends_on: 
      - clipsmart-backend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - clipsmartnetwork

  clipsmart-backend:
    container_name: clipsmart-be
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      MONGODB_URL: ${MONGODB_URL}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      CLIENT_PROJECT_ID: ${CLIENT_PROJECT_ID}
      AUTH_URI: ${AUTH_URI}
      TOKEN_URI: ${TOKEN_URI}
      AUTH_PROVIDER_X509_CERT_URL: ${AUTH_PROVIDER_X509_CERT_URL}
      CLIENT_SECRET: ${CLIENT_SECRET}
      JAVASCRIPT_ORIGINS: ${JAVASCRIPT_ORIGINS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    networks:
      - clipsmartnetwork

networks:
  clipsmartnetwork:
    driver: bridge
