services:
  - type: web
    name: clipsmart-transcript-api
    env: python
    buildCommand: cd python_backend && pip install -r requirements.txt
    startCommand: cd python_backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PROXY_URL
        sync: false
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        fromService:
          type: web
          name: clipsmart-transcript-api
          envVarKey: PORT 